# Generated by Django 3.1.7 on 2021-04-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
