# Generated by Django 3.1.7 on 2021-04-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210403_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='project_id',
            new_name='project',
        ),
    ]
