# Generated by Django 3.1.7 on 2021-04-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210406_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_donate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
