# Generated by Django 3.1.7 on 2021-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='body_comment',
            field=models.TextField(default='content', max_length=4000),
        ),
        migrations.AlterField(
            model_name='reportproject',
            name='body_project',
            field=models.TextField(default='content', max_length=4000),
        ),
    ]
